server:
  port: 8080


spring:
  cloud:
    gateway:
      routes:
        - id: app-api
          uri: http://localhost:8081
          predicates:
            - Path=/app/**
        - id: resv-api
          uri: http://localhost:8082
          predicates:
            - Path=/resv/**

