server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: app-api
          uri: http://localhost:8081
          predicates:
            - Path=/login,/app/**
        - id: resv-api
          uri: http://localhost:8082
          predicates:
            - Path=/resv/**

