project:
  upload:
    path: "C:/upload"

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_ID}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION} # AWS_REGION 환경 변수 사용
      s3:
        bucket: eatzzy

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
